project_id = "jargwnvrejwtfcqcerjl"

[functions.ai-chat]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.send-order-sms]
verify_jwt = false
